spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: -1ms
        max-active: 8
        min-idle: 0
        max-idle: 8
  #前端使用jsp页面
  mvc:
    view:
      prefix: /WEB/views/
      suffix: .jsp
  #AOP
  aop:
    auto: true
    proxy-target-class: false
  #发送邮件              gneumrtcneqybdei
  mail:
    host: smtp.qq.com
    username: 1060891243@qq.com
    #邮箱开启smtp服务的授权码
    password: gneumrtcneqybdei
    default-encoding: UTF-8
    port: 587

#邮件发送人
main.fromMail.addr: 1060891243@qq.com


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zjj.exercise.model  # 注意：对应实体类的路径

#logging:
 # config: classpath:log4j.properties
